theme: jekyll-theme-architect
show_downloads: [true]
github:
  zip_url: https://github.com/gotchamana/StickyNotes/releases/download/v0.9/StcikyNotes.exe.zip
  tar_url: https://github.com/gotchamana/StickyNotes/releases/download/v0.9/StickyNotes.jar.zip
